var select = document.getElementById("1"); 
var options = ["1", "2", "3", "4", "5"]; 
 

/* JavaScript file Generated by
 * Creativyst(tm) CSV converter
 *   (www.creativyst.com)
 * 
 * (C) Copyright 2002-2003, Creativyst, Inc.
 * 
 * Permission is hereby granted to use,
 * distribute, and change this file for any
 * reason, provided this entire comment remains
 * intact with the work.
 * 
 *
*/

/*JSCPragma:StartCompress
*/

var cat_no = 21;

var Col0 = Array([cat_no]);

Col0[0] = "Category";

Col0[1] = "706";

Col0[2] = "799";

Col0[3] = "1703";

Col0[4] = "1726";

Col0[5] = "2119";

Col0[6] = "2202";

Col0[7] = "3203";

Col0[8] = "3504";

Col0[9] = "3509";

Col0[10] = "4401";

Col0[11] = "4517";

Col0[12] = "5122";

Col0[13] = "5558";

Col0[14] = "5616";

Col0[15] = "5619";

Col0[16] = "5824";

Col0[17] = "6202";

Col0[18] = "7205";

Col0[19] = "9115";

Col0[20] = "9909";
// Optional: Clear all existing options first:
select.innerHTML = "";
// Populate list with options:
for(var i = 0; i < cat_no; i++) {
    var opt = Col0[i];
    select.innerHTML += "<option value=\"" + opt + "\">" + opt + "</option>";
}




var select = document.getElementById("2"); 
var brand_no = 76;

var brand = Array([brand_no]);

brand[0] = "Brand";

brand[1] = "5";

brand[2] = "47";

brand[3] = "174";

brand[4] = "182";

brand[5] = "222";

brand[6] = "304";

brand[7] = "305";

brand[8] = "330";

brand[9] = "343";

brand[10] = "345";

brand[11] = "364";

brand[12] = "365";

brand[13] = "401";

brand[14] = "421";

brand[15] = "484";

brand[16] = "486";

brand[17] = "516";

brand[18] = "518";

brand[19] = "532";

brand[20] = "534";

brand[21] = "569";

brand[22] = "577";

brand[23] = "610";

brand[24] = "648";

brand[25] = "678";

brand[26] = "711";

brand[27] = "726";

brand[28] = "730";

brand[29] = "754";

brand[30] = "763";

brand[31] = "767";

brand[32] = "774";

brand[33] = "804";

brand[34] = "833";

brand[35] = "843";

brand[36] = "860";

brand[37] = "867";

brand[38] = "875";

brand[39] = "885";

brand[40] = "890";

brand[41] = "914";

brand[42] = "1011";

brand[43] = "1030";

brand[44] = "1073";

brand[45] = "1084";

brand[46] = "1224";

brand[47] = "1230";

brand[48] = "1292";

brand[49] = "1298";

brand[50] = "1322";

brand[51] = "1324";

brand[52] = "1358";

brand[53] = "1362";

brand[54] = "1366";

brand[55] = "1414";

brand[56] = "1436";

brand[57] = "1483";

brand[58] = "1564";

brand[59] = "1682";

brand[60] = "1698";

brand[61] = "1706";

brand[62] = "1713";

brand[63] = "1722";

brand[64] = "1748";

brand[65] = "1814";

brand[66] = "1832";

brand[67] = "1841";

brand[68] = "1893";

brand[69] = "1932";

brand[70] = "1967";

brand[71] = "1974";

brand[72] = "2010";

brand[73] = "2014";

brand[74] = "2017";

brand[75] = "2024";







// Optional: Clear all existing options first:
select.innerHTML = "";
// Populate list with options:
for(var i = 0; i < brand_no; i++) {
    var opt = brand[i];
    select.innerHTML += "<option value=\"" + opt + "\">" + opt + "</option>";
}





/*
company dropdown
*/

var select = document.getElementById("3"); 
var company_no = 147;

var company = Array([company_no]);

company[0] = "Company";

company[1] = "1036030";

company[2] = "10100010";

company[3] = "10120010";

company[4] = "10200020";

company[5] = "10433040";

company[6] = "10800484";

company[7] = "10800585";

company[8] = "10848181";

company[9] = "10877686";

company[10] = "10895585";

company[11] = "10940090";

company[12] = "101018717";

company[13] = "101059414";

company[14] = "101066818";

company[15] = "101074212";

company[16] = "101100212";

company[17] = "101101313";

company[18] = "101111010";

company[19] = "101111111";

company[20] = "101112414";

company[21] = "101114616";

company[22] = "101115010";

company[23] = "101115212";

company[24] = "101116111";

company[25] = "101116616";

company[26] = "101117111";

company[27] = "101119010";

company[28] = "101119313";

company[29] = "101121313";

company[30] = "101121818";

company[31] = "101122515";

company[32] = "101125919";

company[33] = "101127414";

company[34] = "101129111";

company[35] = "101153515";

company[36] = "101154717";

company[37] = "101159616";

company[38] = "101182212";

company[39] = "101192414";

company[40] = "101200010";

company[41] = "101200515";

company[42] = "101217616";

company[43] = "101238818";

company[44] = "101240010";

company[45] = "101246313";

company[46] = "101263616";

company[47] = "101284212";

company[48] = "101296515";

company[49] = "101300010";

company[50] = "101300818";

company[51] = "101330818";

company[52] = "101345111";

company[53] = "101345414";

company[54] = "101366919";

company[55] = "101385111";

company[56] = "101396414";

company[57] = "101398515";

company[58] = "101400010";

company[59] = "101429919";

company[60] = "101433818";

company[61] = "101435313";

company[62] = "101461313";

company[63] = "101461515";

company[64] = "101471717";

company[65] = "101510818";

company[66] = "101516616";

company[67] = "101548111";

company[68] = "101590010";

company[69] = "101598414";

company[70] = "101616515";

company[71] = "101626414";

company[72] = "101644717";

company[73] = "101686717";

company[74] = "101707717";

company[75] = "101750010";

company[76] = "101775212";

company[77] = "101790010";

company[78] = "101791111";

company[79] = "101798717";

company[80] = "101820010";

company[81] = "101839717";

company[82] = "101851515";

company[83] = "101858212";

company[84] = "101861919";

company[85] = "101878717";

company[86] = "101906414";

company[87] = "101920010";

company[88] = "101930111";

company[89] = "101944717";

company[90] = "101947313";

company[91] = "101960010";

company[92] = "101980010";

company[93] = "101995111";

company[94] = "102001828";

company[95] = "102011020";

company[96] = "102018828";

company[97] = "102027222";

company[98] = "102032323";

company[99] = "102047121";

company[100] = "102050525";

company[101] = "102055525";

company[102] = "102065222";

company[103] = "102072828";

company[104] = "102073525";

company[105] = "102080020";

company[106] = "102082626";

company[107] = "102100020";

company[108] = "102111020";

company[109] = "102112020";

company[110] = "102113020";

company[111] = "102113121";

company[112] = "102114020";

company[113] = "102128525";

company[114] = "102129121";

company[115] = "102135727";

company[116] = "102171424";

company[117] = "102172424";

company[118] = "102182222";

company[119] = "102183424";

company[120] = "102219828";

company[121] = "102222929";

company[122] = "102230424";

company[123] = "102240020";

company[124] = "102248121";

company[125] = "102250626";

company[126] = "102251828";

company[127] = "102261828";

company[128] = "102265525";

company[129] = "102300525";

company[130] = "102301222";

company[131] = "102316929";

company[132] = "102326929";

company[133] = "102327828";

company[134] = "102340020";

company[135] = "102345626";

company[136] = "102354525";

company[137] = "102357525";

company[138] = "102370020";

company[139] = "102382929";

company[140] = "102393323";

company[141] = "102410525";

company[142] = "102420020";

company[143] = "102421121";

company[144] = "102429121";

company[145] = "102444222";

company[146] = "102445222";

// Populate list with options:
for(var i = 0; i < 147; i++) {
    var opt = company[i];
    select.innerHTML += "<option value=\"" + opt + "\">" + opt + "</option>";
}

